defaults:
  bytesToRead: 100

clientDefaults:
  serverPort: "127.0.0.1:50001"
  usage: False

serverDefaults:
  listenPort: 50001
  listenAddress: ''       # Symbolic name meaning all available interfaces
  usage: False

debugging:
  debug: False
